import { Expense } from "../models/expense.model";
import { Budget } from "../models/budget.model";

export const INITIAL_SAMPLE_EXPENSES: Expense[] = [
  {
    id: "exp-1",
    title: "AWS Cloud Infrastructure - Production EKS & RDS",
    amount: 5420.50,
    currency: "EUR",
    category: "Cloud & Infrastructure",
    date: "2026-08-01",
    paymentMethod: "Corporate Card",
    status: "cleared",
    vendor: "Amazon Web Services EMEA",
    description: "Monthly production compute, Kubernetes clusters and multi-AZ database storage.",
    department: "Engineering",
    tags: ["AWS", "Production", "Cloud"],
    receiptUrl: "https://example.com/receipts/aws-aug-2026.pdf",
    createdAt: "2026-08-01T08:00:00Z",
    updatedAt: "2026-08-01T08:00:00Z"
  },
  {
    id: "exp-2",
    title: "GitHub Enterprise & Copilot Subscription",
    amount: 1450.00,
    currency: "EUR",
    category: "Software & SaaS",
    date: "2026-08-03",
    paymentMethod: "Corporate Card",
    status: "cleared",
    vendor: "GitHub Inc.",
    description: "Annual Enterprise Cloud seat licenses + AI Copilot for 50 engineers.",
    department: "Engineering",
    tags: ["DevTools", "AI", "GitHub"],
    createdAt: "2026-08-03T10:30:00Z",
    updatedAt: "2026-08-03T10:30:00Z"
  },
  {
    id: "exp-3",
    title: "Google Workspace & GCP BigQuery",
    amount: 2180.00,
    currency: "EUR",
    category: "Cloud & Infrastructure",
    date: "2026-08-05",
    paymentMethod: "Direct Debit",
    status: "cleared",
    vendor: "Google Ireland Ltd",
    description: "Company emails, drive storage, and data analytics queries.",
    department: "Operations",
    tags: ["Google", "Infrastructure", "Analytics"],
    createdAt: "2026-08-05T09:15:00Z",
    updatedAt: "2026-08-05T09:15:00Z"
  },
  {
    id: "exp-4",
    title: "Senior Fullstack Contractor - Sprint 18",
    amount: 6800.00,
    currency: "EUR",
    category: "Salaries & Contractors",
    date: "2026-08-08",
    paymentMethod: "Bank Transfer",
    status: "cleared",
    vendor: "Nordic Tech Consulting AB",
    description: "Specialized Angular 19 frontend migration support.",
    department: "Engineering",
    tags: ["Contractor", "Frontend", "Angular"],
    createdAt: "2026-08-08T14:00:00Z",
    updatedAt: "2026-08-08T14:00:00Z"
  },
  {
    id: "exp-5",
    title: "Google Ads & LinkedIn Sponsored Campaigns",
    amount: 3200.00,
    currency: "EUR",
    category: "Marketing & Ads",
    date: "2026-08-10",
    paymentMethod: "Corporate Card",
    status: "cleared",
    vendor: "LinkedIn Ireland & Google Ads",
    description: "Q3 B2B lead generation campaign for enterprise tier.",
    department: "Marketing",
    tags: ["Ads", "B2B", "Growth"],
    createdAt: "2026-08-10T11:20:00Z",
    updatedAt: "2026-08-10T11:20:00Z"
  },
  {
    id: "exp-6",
    title: "WeWork Office Lease - Berlin Hub",
    amount: 4200.00,
    currency: "EUR",
    category: "Office & Facilities",
    date: "2026-08-01",
    paymentMethod: "Bank Transfer",
    status: "recurring",
    vendor: "WeWork Germany GmbH",
    description: "Monthly dedicated office space for 12 team members.",
    department: "Operations",
    tags: ["Office", "Rent", "Recurring"],
    createdAt: "2026-08-01T00:00:00Z",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "exp-7",
    title: "KubeCon EU 2026 Flights & Hotels",
    amount: 1950.40,
    currency: "EUR",
    category: "Travel & Events",
    date: "2026-08-12",
    paymentMethod: "Corporate Card",
    status: "cleared",
    vendor: "Lufthansa & Marriott Hotels",
    description: "Travel expenses for 2 platform engineers attending conference.",
    department: "Engineering",
    tags: ["Conference", "Travel", "DevOps"],
    createdAt: "2026-08-12T16:45:00Z",
    updatedAt: "2026-08-12T16:45:00Z"
  },
  {
    id: "exp-8",
    title: "SOC 2 Type II Annual Audit Retainer",
    amount: 4500.00,
    currency: "EUR",
    category: "Legal & Compliance",
    date: "2026-08-14",
    paymentMethod: "Bank Transfer",
    status: "pending",
    vendor: "Securiti Legal LLP",
    description: "Interim compliance review and automated evidence collection audit.",
    department: "Security & Legal",
    tags: ["Security", "Compliance", "SOC2"],
    createdAt: "2026-08-14T09:00:00Z",
    updatedAt: "2026-08-14T09:00:00Z"
  },
  {
    id: "exp-9",
    title: "Apple MacBook Pro M4 Max (x2)",
    amount: 4899.00,
    currency: "EUR",
    category: "Equipment & Hardware",
    date: "2026-08-15",
    paymentMethod: "Corporate Card",
    status: "pending",
    vendor: "Apple Retail Germany",
    description: "Hardware refresh for new lead architects.",
    department: "Engineering",
    tags: ["Hardware", "Laptops", "Apple"],
    createdAt: "2026-08-15T15:30:00Z",
    updatedAt: "2026-08-15T15:30:00Z"
  },
  {
    id: "exp-10",
    title: "Slack & Notion Enterprise Workspaces",
    amount: 980.00,
    currency: "EUR",
    category: "Software & SaaS",
    date: "2026-08-16",
    paymentMethod: "Corporate Card",
    status: "recurring",
    vendor: "Salesforce / Notion Labs",
    description: "Collaboration and internal documentation tooling.",
    department: "Operations",
    tags: ["SaaS", "Productivity"],
    createdAt: "2026-08-16T12:00:00Z",
    updatedAt: "2026-08-16T12:00:00Z"
  },
  {
    id: "exp-11",
    title: "Datadog APM & Log Management",
    amount: 1850.00,
    currency: "EUR",
    category: "Cloud & Infrastructure",
    date: "2026-07-28",
    paymentMethod: "Corporate Card",
    status: "cleared",
    vendor: "Datadog Inc.",
    description: "Application performance monitoring and distributed tracing.",
    department: "Engineering",
    tags: ["Monitoring", "Cloud", "DevOps"],
    createdAt: "2026-07-28T09:00:00Z",
    updatedAt: "2026-07-28T09:00:00Z"
  },
  {
    id: "exp-12",
    title: "Figma Enterprise Design System Seats",
    amount: 620.00,
    currency: "EUR",
    category: "Software & SaaS",
    date: "2026-07-25",
    paymentMethod: "Corporate Card",
    status: "cleared",
    vendor: "Figma Inc.",
    description: "Design licenses for UI/UX product teams.",
    department: "Product",
    tags: ["Design", "UI/UX"],
    createdAt: "2026-07-25T11:00:00Z",
    updatedAt: "2026-07-25T11:00:00Z"
  }
];

export const INITIAL_SAMPLE_BUDGETS: Budget[] = [
  {
    id: "bud-1",
    category: "Cloud & Infrastructure",
    monthlyLimit: 12000,
    period: "2026-08",
    alertThresholdPercent: 80,
    notes: "AWS, GCP, Datadog and CDN infrastructure",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "bud-2",
    category: "Salaries & Contractors",
    monthlyLimit: 15000,
    period: "2026-08",
    alertThresholdPercent: 85,
    notes: "External contractor invoices & specialist advisory",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "bud-3",
    category: "Software & SaaS",
    monthlyLimit: 5000,
    period: "2026-08",
    alertThresholdPercent: 80,
    notes: "GitHub, Slack, Notion, Figma, JetBrains",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "bud-4",
    category: "Marketing & Ads",
    monthlyLimit: 6000,
    period: "2026-08",
    alertThresholdPercent: 75,
    notes: "Google Ads, LinkedIn, SEO agency",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "bud-5",
    category: "Office & Facilities",
    monthlyLimit: 5000,
    period: "2026-08",
    alertThresholdPercent: 90,
    notes: "WeWork co-working desks, supplies, catering",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "bud-6",
    category: "Equipment & Hardware",
    monthlyLimit: 6000,
    period: "2026-08",
    alertThresholdPercent: 80,
    notes: "Laptops, monitors, testing mobile devices",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "bud-7",
    category: "Travel & Events",
    monthlyLimit: 4000,
    period: "2026-08",
    alertThresholdPercent: 80,
    notes: "Client on-site visits & tech conferences",
    updatedAt: "2026-08-01T00:00:00Z"
  },
  {
    id: "bud-8",
    category: "Legal & Compliance",
    monthlyLimit: 5000,
    period: "2026-08",
    alertThresholdPercent: 85,
    notes: "Audits, trademarks, legal consults",
    updatedAt: "2026-08-01T00:00:00Z"
  }
];
